import Bankaprakar from "../views/Forests/Bankaprakar";

const forestRoutes = [
  {
    path: "/forests/samudayikbanlist",
    title: "Samudayikban",
    name: "samudayikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/samudayikbanadd/new",
    title: "Samudayikban",
    name: "samudayikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/samudayikbanedit/:id",
    title: "Samudayikban",
    name: "samudayikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/dharmikbanlist",
    title: "Dharmikban",
    name: "dharmikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/dharmikbanadd/new",
    title: "Dharmikban",
    name: "dharmikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/dharmikbanedit/:id",
    title: "Dharmikban",
    name: "dharmikban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/kabuliyatibanlist",
    title: "Kabuliyatiban",
    name: "kabuliyatiban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/kabuliyatibanadd/new",
    title: "Kabuliyatiban",
    name: "kabuliyatiban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/kabuliyatibanedit/:id",
    title: "Kabuliyatiban",
    name: "kabuliyatiban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/nijibanlist",
    title: "Nijiban",
    name: "nijiban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/nijibanadd/new",
    title: "Nijiban",
    name: "nijiban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/nijibanedit/:id",
    title: "Nijiban",
    name: "nijiban",
    auth: true,
    component: Bankaprakar,
  },

  {
    path: "/forests/sajhedaribanlist",
    title: "Sajhedariban",
    name: "sajhedariban",
    auth: true,
    component: Bankaprakar,
  },

  {
    path: "/forests/sajhedaribanadd/new",
    title: "Sajhedariban",
    name: "sajhedariban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/sajhedaribanedit/:id",
    title: "Sajhedariban",
    name: "sajhedariban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/chaklabanlist",
    title: "Chaklaban",
    name: "chaklaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/chaklabanadd/new",
    title: "Chaklaban",
    name: "chaklaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/chaklabanedit/:id",
    title: "Chaklaban",
    name: "chaklaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/rastriyabanlist",
    title: "Rastriyaban",
    name: "rastriyaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/rastriyabanadd/new",
    title: "Rastriyaban",
    name: "rastriyaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/rastriyabanedit/:id",
    title: "Rastriyaban",
    name: "rastriyaban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/commercialbanlist",
    title: "Commercialban",
    name: "Commercialban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/commercialbanadd/new",
    title: "Commercialban",
    name: "Commercialban",
    auth: true,
    component: Bankaprakar,
  },
  {
    path: "/forests/commercialbanedit/:id",
    title: "Commercialban",
    name: "Commercialban",
    auth: true,
    component: Bankaprakar,
  },

  {
    redirect: true,
    path: "/forests",
    to: "/forests/samudayikbanlist",
    name: "samudayikban",

    component: Bankaprakar,
  },
];

export default forestRoutes;
